version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  blockchain:
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./ethereum:/root/.ethereum

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: protegedollar
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
